# Generated by Django 5.0.1 on 2026-01-22 12:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("members", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("terms_conditions", models.TextField(blank=True)),
                (
                    "promo_type",
                    models.CharField(
                        choices=[
                            ("percent_discount", "Percent Discount"),
                            ("amount_discount", "Amount Discount"),
                            ("buy_x_get_y", "Buy X Get Y (BOGO)"),
                            ("combo", "Combo Deal"),
                            ("free_item", "Free Item"),
                            ("happy_hour", "Happy Hour"),
                            ("cashback", "Cashback"),
                            ("payment_discount", "Payment Method Discount"),
                            ("package", "Package/Set Menu"),
                            ("mix_match", "Mix & Match"),
                            ("upsell", "Upsell/Add-on"),
                            ("threshold_tier", "Threshold/Tiered"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "apply_to",
                    models.CharField(
                        choices=[
                            ("all", "All Products"),
                            ("category", "Specific Categories"),
                            ("product", "Specific Products"),
                            ("bill", "Bill/Subtotal Level"),
                            ("payment", "Payment Method"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("company", "Company-wide"),
                            ("brands", "Multiple Brands"),
                            ("single", "Single Brand"),
                        ],
                        default="company",
                        max_length=20,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cap discount amount",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("buy_quantity", models.IntegerField(default=0)),
                ("get_quantity", models.IntegerField(default=0)),
                (
                    "combo_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "happy_hour_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_methods",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON array: ['cash', 'card', 'qris', 'gopay', 'ovo']",
                    ),
                ),
                (
                    "payment_min_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("member_only", models.BooleanField(default=False)),
                (
                    "member_tiers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON array: ['bronze', 'silver', 'gold', 'platinum']",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "valid_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON array: [0-6] (0=Monday, 6=Sunday)",
                    ),
                ),
                ("valid_time_start", models.TimeField(blank=True, null=True)),
                ("valid_time_end", models.TimeField(blank=True, null=True)),
                ("exclude_holidays", models.BooleanField(default=False)),
                (
                    "max_uses",
                    models.IntegerField(
                        blank=True,
                        help_text="Total max uses (null=unlimited)",
                        null=True,
                    ),
                ),
                (
                    "max_uses_per_customer",
                    models.IntegerField(
                        blank=True, help_text="Max uses per customer", null=True
                    ),
                ),
                ("max_uses_per_day", models.IntegerField(blank=True, null=True)),
                (
                    "current_uses",
                    models.IntegerField(default=0, help_text="Updated by Edge"),
                ),
                (
                    "min_purchase",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("min_quantity", models.IntegerField(default=0)),
                ("min_items", models.IntegerField(default=0)),
                ("is_stackable", models.BooleanField(default=False)),
                (
                    "priority",
                    models.IntegerField(default=0, help_text="Higher = execute first"),
                ),
                (
                    "sales_channels",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="JSON array: ['dine_in', 'takeaway', 'delivery', 'kiosk']",
                    ),
                ),
                ("exclude_channels", models.JSONField(blank=True, default=list)),
                (
                    "customer_type",
                    models.CharField(
                        choices=[
                            ("all", "All Customers"),
                            ("first_order", "First Order Ever"),
                            ("first_per_brand", "First Order per Brand"),
                            ("comeback", "Comeback Customer"),
                            ("inactive", "Inactive Customer"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("inactive_days_threshold", models.IntegerField(default=30)),
                ("is_employee_promo", models.BooleanField(default=False)),
                ("employee_roles", models.JSONField(blank=True, default=list)),
                ("require_manager_approval", models.BooleanField(default=False)),
                ("require_approval_pin", models.BooleanField(default=False)),
                ("allow_manual_override", models.BooleanField(default=False)),
                (
                    "max_manual_discount_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "max_manual_discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("override_requires_approval", models.BooleanField(default=False)),
                ("override_approval_roles", models.JSONField(blank=True, default=list)),
                ("is_upsell", models.BooleanField(default=False)),
                (
                    "upsell_special_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("upsell_message", models.TextField(blank=True)),
                ("is_mix_match", models.BooleanField(default=False)),
                (
                    "mix_match_rules",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON: rules for mix & match",
                    ),
                ),
                (
                    "execution_priority",
                    models.IntegerField(
                        default=500,
                        help_text="1-999, lower executes first",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                (
                    "execution_stage",
                    models.CharField(
                        choices=[
                            ("item_level", "Item Level"),
                            ("subtotal", "Subtotal Level"),
                            ("after_tax", "After Tax"),
                            ("payment", "Payment Level"),
                            ("post_payment", "Post Payment (Cashback)"),
                        ],
                        default="item_level",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_auto_apply",
                    models.BooleanField(
                        default=True, help_text="Auto-apply when conditions met"
                    ),
                ),
                ("require_voucher", models.BooleanField(default=False)),
                ("show_in_menu", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        help_text="For single brand scope only",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="single_brand_promotions",
                        to="core.brand",
                    ),
                ),
                (
                    "brands",
                    models.ManyToManyField(
                        blank=True,
                        related_name="multi_brand_promotions",
                        to="core.brand",
                    ),
                ),
                (
                    "cannot_combine_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="incompatible_promotions",
                        to="promotions.promotion",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="promotions", to="products.category"
                    ),
                ),
                (
                    "combo_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="combo_promotions",
                        to="products.product",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_promotions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exclude_brands",
                    models.ManyToManyField(
                        blank=True, related_name="excluded_promotions", to="core.brand"
                    ),
                ),
                (
                    "exclude_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="excluded_promotions",
                        to="products.category",
                    ),
                ),
                (
                    "exclude_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="excluded_promotions",
                        to="members.member",
                    ),
                ),
                (
                    "exclude_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="excluded_from_promotions",
                        to="products.product",
                    ),
                ),
                (
                    "get_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bogo_promotions",
                        to="products.product",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="direct_promotions",
                        to="products.product",
                    ),
                ),
                (
                    "required_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upsell_required_promotions",
                        to="products.product",
                    ),
                ),
                (
                    "upsell_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="upsell_offer_promotions",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion",
                "verbose_name_plural": "Promotions",
                "db_table": "promotion",
                "ordering": ["-execution_priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackagePromotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("package_name", models.CharField(max_length=200)),
                ("package_sku", models.CharField(max_length=50, unique=True)),
                ("package_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="package_promotions/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("allow_modification", models.BooleanField(default=False)),
                ("min_items_required", models.IntegerField(default=0)),
                ("max_items_allowed", models.IntegerField(default=0)),
                ("track_as_virtual_product", models.BooleanField(default=False)),
                ("auto_deduct_components", models.BooleanField(default=True)),
                (
                    "deduction_strategy",
                    models.CharField(
                        choices=[
                            ("fixed_only", "Fixed Items Only"),
                            ("selected_only", "Selected Items Only"),
                            ("all_components", "All Components"),
                        ],
                        default="all_components",
                        max_length=20,
                    ),
                ),
                (
                    "promotion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="package",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package Promotion",
                "verbose_name_plural": "Package Promotions",
                "db_table": "package_promotion",
            },
        ),
        migrations.CreateModel(
            name="CustomerPromotionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_phone", models.CharField(db_index=True, max_length=20)),
                ("first_order_date", models.DateTimeField()),
                ("first_bill_id", models.UUIDField()),
                ("last_order_date", models.DateTimeField()),
                ("total_orders", models.IntegerField(default=1)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_promotion_history",
                        to="core.brand",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_history",
                        to="members.member",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_history",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Promotion History",
                "verbose_name_plural": "Customer Promotion Histories",
                "db_table": "customer_promotion_history",
            },
        ),
        migrations.CreateModel(
            name="PromotionApproval",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bill_id", models.UUIDField(help_text="Reference to Bill")),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("manual_discount", "Manual Discount"),
                            ("employee_promo", "Employee Promo"),
                            ("override", "Override Rules"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("request_reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("approval_pin", models.CharField(blank=True, max_length=6)),
                ("approval_notes", models.TextField(blank=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to="promotions.promotion",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Approval",
                "verbose_name_plural": "Promotion Approvals",
                "db_table": "promotion_approval",
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bill_id", models.UUIDField(help_text="Reference to Bill")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                            ("override", "Manager Override"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Why applied/skipped/failed")),
                ("validation_details", models.JSONField(blank=True, default=dict)),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "final_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("approval_pin_entered", models.BooleanField(default=False)),
                ("override_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_promotion_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Log",
                "verbose_name_plural": "Promotion Logs",
                "db_table": "promotion_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionTier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tier_name", models.CharField(max_length=200)),
                ("tier_order", models.IntegerField()),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percent Discount"),
                            ("amount", "Amount Discount"),
                            ("free_product", "Free Product"),
                            ("points_multiplier", "Points Multiplier"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "points_multiplier",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "free_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tier_free_products",
                        to="products.product",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Tier",
                "verbose_name_plural": "Promotion Tiers",
                "db_table": "promotion_tier",
                "ordering": ["tier_order"],
            },
        ),
        migrations.CreateModel(
            name="PromotionUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                ("bill_id", models.UUIDField(help_text="Reference to Bill")),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("used_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_usages",
                        to="core.brand",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotion_usages",
                        to="members.member",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usages",
                        to="promotions.promotion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion Usage",
                "verbose_name_plural": "Promotion Usages",
                "db_table": "promotion_usage",
                "ordering": ["-used_at"],
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("used", "Used"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                ("customer_name", models.CharField(blank=True, max_length=200)),
                ("qr_code", models.CharField(blank=True, max_length=200)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "used_bill",
                    models.UUIDField(
                        blank=True, help_text="Reference to Bill", null=True
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vouchers",
                        to="promotions.promotion",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="used_vouchers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Voucher",
                "verbose_name_plural": "Vouchers",
                "db_table": "voucher",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PackageItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("fixed", "Fixed Item"), ("choice", "Choice Item")],
                        max_length=10,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("is_required", models.BooleanField(default=True)),
                ("min_selection", models.IntegerField(default=0)),
                ("max_selection", models.IntegerField(default=1)),
                (
                    "upsell_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("upsell_options", models.JSONField(blank=True, default=list)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="For choice items (choose from category)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="For fixed items",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.product",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="promotions.packagepromotion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Package Item",
                "verbose_name_plural": "Package Items",
                "db_table": "package_item",
                "ordering": ["sort_order"],
                "unique_together": {("package", "sort_order")},
            },
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["company", "is_active", "start_date", "end_date"],
                name="promotion_company_ca5c91_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["scope", "is_active"], name="promotion_scope_c47045_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["promo_type"], name="promotion_promo_t_2a380f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(fields=["code"], name="promotion_code_457fc9_idx"),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["execution_priority"], name="promotion_executi_6a330a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="packagepromotion",
            index=models.Index(
                fields=["package_sku"], name="package_pro_package_70dbf4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customerpromotionhistory",
            index=models.Index(
                fields=["customer_phone", "brand"],
                name="customer_pr_custome_134a96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customerpromotionhistory",
            index=models.Index(
                fields=["member", "last_order_date"],
                name="customer_pr_member__736489_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customerpromotionhistory",
            unique_together={("member", "brand", "promotion")},
        ),
        migrations.AddIndex(
            model_name="promotionapproval",
            index=models.Index(
                fields=["bill_id", "status"], name="promotion_a_bill_id_821c45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promotionapproval",
            index=models.Index(
                fields=["requested_by", "requested_at"],
                name="promotion_a_request_db81a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promotionlog",
            index=models.Index(
                fields=["bill_id", "status"], name="promotion_l_bill_id_88c8e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="promotionlog",
            index=models.Index(
                fields=["promotion", "status", "created_at"],
                name="promotion_l_promoti_ff654f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promotiontier",
            index=models.Index(
                fields=["promotion", "min_amount", "is_active"],
                name="promotion_t_promoti_93428d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promotiontier",
            unique_together={("promotion", "tier_order")},
        ),
        migrations.AddIndex(
            model_name="promotionusage",
            index=models.Index(
                fields=["promotion", "member", "used_at"],
                name="promotion_u_promoti_9ac739_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promotionusage",
            index=models.Index(
                fields=["promotion", "customer_phone", "used_at"],
                name="promotion_u_promoti_dc6cd3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="promotionusage",
            index=models.Index(
                fields=["promotion", "used_at"], name="promotion_u_promoti_078a3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["promotion", "status"], name="voucher_promoti_9d896c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(fields=["code"], name="voucher_code_8bda2a_idx"),
        ),
        migrations.AddIndex(
            model_name="voucher",
            index=models.Index(
                fields=["expires_at"], name="voucher_expires_f90a33_idx"
            ),
        ),
    ]
