# Generated by Django 5.0.1 on 2026-01-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0001_initial"),
        ("core", "0008_add_store_to_tablearea"),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='all_stores',
            field=models.BooleanField(default=True, help_text='Apply to all stores in scope (company/brand)'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='stores',
            field=models.ManyToManyField(blank=True, help_text='Specific stores (if all_stores=False)', related_name='promotions', to='core.store'),
        ),
    ]
