# Generated by Django 5.0.1 on 2026-01-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_store_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for company-wide users",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="core.brand",
            ),
        ),
    ]
