# Generated by Django 5.0.1 on 2026-01-23 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_user_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to="core.company",
            ),
        ),
    ]
