# Generated by Django 5.2.10 on 2026-01-24 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Leave blank for brand/company-wide users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.store'),
        ),
    ]
