# Generated by Django 5.0.1 on 2026-01-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_user_store"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role_scope",
            field=models.CharField(
                choices=[
                    ("global", "Global Level"),
                    ("company", "Company Level"),
                    ("brand", "Brand Level"),
                    ("store", "Store Level"),
                ],
                default="store",
                help_text="Authorization scope for this user",
                max_length=20,
            ),
        ),
    ]
