# Generated by Django 5.0.1 on 2026-01-22 12:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_code",
                    models.CharField(help_text="Unique per brand", max_length=50),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("raw_material", "Raw Material"),
                            ("semi_finished", "Semi-Finished"),
                            ("finished_goods", "Finished Goods"),
                            ("packaging", "Packaging"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "base_unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("gram", "Gram"),
                            ("liter", "Liter"),
                            ("ml", "Milliliter"),
                            ("pcs", "Pieces"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        decimal_places=3,
                        default=1,
                        help_text="e.g., 1 kg = 1000 gram",
                        max_digits=10,
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="For FIFO costing",
                        max_digits=10,
                    ),
                ),
                ("track_stock", models.BooleanField(default=True)),
                (
                    "min_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "max_stock",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_items",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "db_table": "inventory_item",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipe_code", models.CharField(max_length=50)),
                ("recipe_name", models.CharField(max_length=200)),
                (
                    "version",
                    models.IntegerField(default=1, help_text="Recipe versioning"),
                ),
                (
                    "yield_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Output quantity per batch",
                        max_digits=10,
                    ),
                ),
                ("yield_unit", models.CharField(max_length=20)),
                (
                    "preparation_type",
                    models.CharField(
                        choices=[
                            ("prep", "Preparation"),
                            ("cook", "Cooking"),
                            ("fry", "Frying"),
                            ("assemble", "Assembly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("effective_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipes",
                        to="core.brand",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipes",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe",
                "verbose_name_plural": "Recipes",
                "db_table": "recipe",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("unit", models.CharField(max_length=20)),
                (
                    "yield_factor",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Loss during prep/cook (e.g., 0.70 = 30% loss)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "is_critical",
                    models.BooleanField(default=False, help_text="Cannot substitute"),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recipe_uses",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="inventory.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recipe Ingredient",
                "verbose_name_plural": "Recipe Ingredients",
                "db_table": "recipe_ingredient",
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["brand", "is_active"], name="inventory_i_brand_i_00ebea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["item_code"], name="inventory_i_item_co_e61695_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["item_type"], name="inventory_i_item_ty_3448a3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together={("brand", "item_code")},
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["brand", "is_active"], name="recipe_brand_i_5a5f56_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["product", "is_active"], name="recipe_product_f8e334_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recipe",
            unique_together={("brand", "product", "version")},
        ),
        migrations.AddIndex(
            model_name="recipeingredient",
            index=models.Index(
                fields=["recipe"], name="recipe_ingr_recipe__cd569f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recipeingredient",
            index=models.Index(
                fields=["inventory_item"], name="recipe_ingr_invento_51b654_idx"
            ),
        ),
    ]
