# Generated by Django 5.0.1 on 2026-01-22 22:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "Stock In"),
                            ("out", "Stock Out"),
                            ("adjustment", "Adjustment"),
                            ("transfer", "Transfer"),
                            ("production", "Production Use"),
                            ("waste", "Waste/Spoilage"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=10)),
                ("unit", models.CharField(max_length=20)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True, help_text="PO/SO/Transfer number", max_length=100
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("movement_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inventory_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.inventoryitem",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="core.store",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Movement",
                "verbose_name_plural": "Stock Movements",
                "db_table": "stock_movement",
                "ordering": ["-movement_date"],
                "indexes": [
                    models.Index(
                        fields=["store", "movement_date"],
                        name="stock_movem_store_i_19bf08_idx",
                    ),
                    models.Index(
                        fields=["inventory_item", "movement_date"],
                        name="stock_movem_invento_37c582_idx",
                    ),
                    models.Index(
                        fields=["movement_type"], name="stock_movem_movemen_e7bdd6_idx"
                    ),
                ],
            },
        ),
    ]
