# Generated by Django 5.0.1 on 2026-01-22 12:22

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("brand_id", models.UUIDField(db_index=True)),
                ("store_id", models.UUIDField(db_index=True)),
                ("terminal_id", models.UUIDField()),
                (
                    "bill_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "bill_type",
                    models.CharField(
                        choices=[
                            ("DINE_IN", "Dine In"),
                            ("TAKEAWAY", "Takeaway"),
                            ("DELIVERY", "Delivery"),
                            ("QRORDER", "QR Order"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("PAID", "Paid"),
                            ("VOID", "Void"),
                            ("REFUND", "Refund"),
                            ("PARTIAL_REFUND", "Partial Refund"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("table_id", models.UUIDField(blank=True, null=True)),
                (
                    "table_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("pax", models.PositiveIntegerField(default=1)),
                ("member_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("member_code", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "customer_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "customer_phone",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "service_charge_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "service_charge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rounding_adjustment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_by", models.UUIDField()),
                ("created_at", models.DateTimeField(db_index=True)),
                ("closed_by", models.UUIDField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("voided_by", models.UUIDField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("voided_reason", models.TextField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "bill",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company_id", "created_at"],
                        name="bill_company_date_idx",
                    ),
                    models.Index(
                        fields=["brand_id", "store_id", "status", "created_at"],
                        name="bill_brand_store_idx",
                    ),
                    models.Index(fields=["bill_number"], name="bill_number_idx"),
                    models.Index(
                        fields=["status", "created_at"], name="bill_status_date_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bill_id", models.UUIDField(db_index=True)),
                ("company_id", models.UUIDField(db_index=True)),
                ("brand_id", models.UUIDField(db_index=True)),
                ("store_id", models.UUIDField(db_index=True)),
                ("product_id", models.UUIDField()),
                ("product_sku", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=300)),
                ("category_id", models.UUIDField(blank=True, null=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT_TO_KITCHEN", "Sent to Kitchen"),
                            ("PREPARING", "Preparing"),
                            ("READY", "Ready"),
                            ("SERVED", "Served"),
                            ("VOID", "Void"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_void", models.BooleanField(db_index=True, default=False)),
                ("void_reason", models.TextField(blank=True, null=True)),
                ("modifiers_snapshot", models.JSONField(blank=True, default=list)),
                ("kitchen_station_id", models.UUIDField(blank=True, null=True)),
                ("sent_to_kitchen_at", models.DateTimeField(blank=True, null=True)),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("created_by", models.UUIDField()),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("voided_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "bill_item",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["bill_id", "is_void", "status"],
                        name="billitem_bill_status_idx",
                    ),
                    models.Index(
                        fields=["company_id", "brand_id", "created_at"],
                        name="billitem_company_idx",
                    ),
                    models.Index(
                        fields=["product_id", "created_at"], name="billitem_product_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BillPromotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bill_id", models.UUIDField(db_index=True)),
                ("promotion_id", models.UUIDField()),
                ("promotion_name", models.CharField(max_length=300)),
                (
                    "promotion_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "execution_stage",
                    models.CharField(
                        choices=[
                            ("ITEM_LEVEL", "Item Level"),
                            ("SUBTOTAL", "Subtotal"),
                            ("PAYMENT", "Payment"),
                            ("CASHBACK", "Cashback"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cashback_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("affected_items", models.JSONField(blank=True, default=list)),
                ("calculation_detail", models.JSONField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(db_index=True)),
                ("applied_by", models.UUIDField()),
            ],
            options={
                "db_table": "bill_promotion",
                "ordering": ["applied_at"],
                "indexes": [
                    models.Index(
                        fields=["bill_id", "applied_at"], name="billpromo_bill_idx"
                    ),
                    models.Index(
                        fields=["promotion_id", "applied_at"],
                        name="billpromo_promo_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BillRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_bill_id", models.UUIDField(db_index=True)),
                ("refund_bill_id", models.UUIDField(blank=True, null=True)),
                (
                    "refund_type",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Refund"),
                            ("PARTIAL", "Partial Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("refunded_items", models.JSONField(blank=True, default=list)),
                ("requested_at", models.DateTimeField(db_index=True)),
                ("requested_by", models.UUIDField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.UUIDField(blank=True, null=True)),
                ("approval_notes", models.TextField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "bill_refund",
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["original_bill_id", "status"],
                        name="refund_bill_status_idx",
                    ),
                    models.Index(
                        fields=["status", "requested_at"], name="refund_status_date_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CashDrop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_id", models.UUIDField(db_index=True)),
                ("brand_id", models.UUIDField(db_index=True)),
                ("store_id", models.UUIDField(db_index=True)),
                ("terminal_id", models.UUIDField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("DROP", "Drop"), ("PICKUP", "Pickup")], max_length=20
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("created_by", models.UUIDField()),
            ],
            options={
                "db_table": "cash_drop",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company_id", "brand_id", "store_id", "created_at"],
                        name="cashdrop_store_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CashierShift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("store_session_id", models.UUIDField(db_index=True)),
                ("terminal_id", models.UUIDField(db_index=True)),
                ("cashier_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "opening_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "closing_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "expected_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "variance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("opened_at", models.DateTimeField(db_index=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "cashier_shift",
                "ordering": ["-opened_at"],
                "indexes": [
                    models.Index(
                        fields=["store_session_id", "terminal_id"],
                        name="shift_session_terminal_idx",
                    ),
                    models.Index(
                        fields=["cashier_id", "opened_at"], name="shift_cashier_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("store_id", models.UUIDField(db_index=True)),
                ("brand_id", models.UUIDField(db_index=True)),
                ("company_id", models.UUIDField(db_index=True)),
                ("inventory_item_id", models.UUIDField(db_index=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("SALE", "Sale"),
                            ("REFUND", "Refund"),
                            ("WASTE", "Waste"),
                            ("ADJUSTMENT", "Adjustment"),
                            ("TRANSFER_IN", "Transfer In"),
                            ("TRANSFER_OUT", "Transfer Out"),
                            ("MANUFACTURING", "Manufacturing"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit", models.CharField(max_length=50)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("bill_id", models.UUIDField(blank=True, null=True)),
                ("bill_item_id", models.UUIDField(blank=True, null=True)),
                ("recipe_id", models.UUIDField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("created_by", models.UUIDField()),
            ],
            options={
                "db_table": "inventory_movement",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["inventory_item_id", "created_at"],
                        name="invmov_item_date_idx",
                    ),
                    models.Index(
                        fields=["store_id", "movement_type", "created_at"],
                        name="invmov_store_type_idx",
                    ),
                    models.Index(fields=["bill_id"], name="invmov_bill_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="KitchenOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bill_id", models.UUIDField(db_index=True)),
                ("bill_item_id", models.UUIDField()),
                ("kitchen_station_id", models.UUIDField(db_index=True)),
                ("product_name", models.CharField(max_length=300)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PREPARING", "Preparing"),
                            ("READY", "Ready"),
                            ("SERVED", "Served"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("printed_at", models.DateTimeField(db_index=True)),
                ("prepared_at", models.DateTimeField(blank=True, null=True)),
                ("served_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "kitchen_order",
                "ordering": ["printed_at"],
                "indexes": [
                    models.Index(
                        fields=["bill_id", "status"], name="kitchen_bill_status_idx"
                    ),
                    models.Index(
                        fields=["kitchen_station_id", "status", "printed_at"],
                        name="kitchen_station_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bill_id", models.UUIDField(db_index=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("QRIS", "QRIS"),
                            ("EWALLET", "E-Wallet"),
                            ("TRANSFER", "Bank Transfer"),
                            ("VOUCHER", "Voucher"),
                            ("MEMBER_POINTS", "Member Points"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("REFUND", "Refund"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "cash_received",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "change",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "external_reference",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("payment_gateway_response", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("created_by", models.UUIDField()),
            ],
            options={
                "db_table": "payment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["bill_id", "created_at"], name="payment_bill_idx"
                    ),
                    models.Index(
                        fields=["payment_method", "status"],
                        name="payment_method_status_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StoreSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("store_id", models.UUIDField(db_index=True)),
                ("brand_id", models.UUIDField(db_index=True)),
                ("company_id", models.UUIDField(db_index=True)),
                ("session_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Open"), ("CLOSED", "Closed")],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "opening_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "closing_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "expected_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "variance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_refund",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("opened_at", models.DateTimeField()),
                ("opened_by", models.UUIDField()),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_by", models.UUIDField(blank=True, null=True)),
            ],
            options={
                "db_table": "store_session",
                "ordering": ["-session_date"],
                "indexes": [
                    models.Index(
                        fields=["store_id", "session_date"],
                        name="session_store_date_idx",
                    ),
                    models.Index(
                        fields=["company_id", "session_date"],
                        name="session_company_date_idx",
                    ),
                ],
                "unique_together": {("store_id", "session_date")},
            },
        ),
    ]
