# Generated by Django 5.0.1 on 2026-01-22 11:58

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "member_code",
                    models.CharField(
                        help_text="Auto-generated: MB-COMPANYCODE-YYYYMM-XXXX",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True, help_text="Physical card number", max_length=50
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="bronze",
                        max_length=20,
                    ),
                ),
                ("joined_date", models.DateField(default=django.utils.timezone.now)),
                ("expire_date", models.DateField(blank=True, null=True)),
                (
                    "points",
                    models.IntegerField(
                        default=0,
                        help_text="Loyalty points balance",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "point_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monetary balance (from redeemed points or top-up)",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "total_visits",
                    models.IntegerField(default=0, help_text="Total number of visits"),
                ),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total amount spent",
                        max_digits=12,
                    ),
                ),
                ("last_visit", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="core.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registered_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Member",
                "verbose_name_plural": "Members",
                "db_table": "member",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MemberTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bill_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Reference to Bill (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earn", "Earn Points"),
                            ("redeem", "Redeem Points"),
                            ("topup", "Balance Top-up"),
                            ("payment", "Payment using Balance"),
                            ("refund", "Refund"),
                            ("adjustment", "Manual Adjustment"),
                            ("expired", "Points Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "points_change",
                    models.IntegerField(
                        default=0, help_text="Points change (+earn, -redeem/expired)"
                    ),
                ),
                ("points_before", models.IntegerField(default=0)),
                ("points_after", models.IntegerField(default=0)),
                (
                    "balance_change",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Balance change (+topup/refund, -payment)",
                        max_digits=12,
                    ),
                ),
                (
                    "balance_before",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "balance_after",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, help_text="External reference", max_length=200
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="member_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "Member Transaction",
                "verbose_name_plural": "Member Transactions",
                "db_table": "member_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["company", "member_code"], name="member_company_532b5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["company", "phone"], name="member_company_8da75f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["tier", "is_active"], name="member_tier_ab20da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["company", "is_active"], name="member_company_00a770_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membertransaction",
            index=models.Index(
                fields=["member", "created_at"], name="member_tran_member__3f42f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membertransaction",
            index=models.Index(
                fields=["transaction_type", "created_at"],
                name="member_tran_transac_e1568e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membertransaction",
            index=models.Index(
                fields=["bill_id"], name="member_tran_bill_id_00e334_idx"
            ),
        ),
    ]
