# Generated by Django 5.0.1 on 2026-01-22 11:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "sort_order",
                    models.IntegerField(default=0, help_text="Display order"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon name or path", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categories",
                        to="core.brand",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category for hierarchical structure",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "category",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="KitchenStation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kitchen Station",
                "verbose_name_plural": "Kitchen Stations",
                "db_table": "kitchen_station",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["code"], name="kitchen_sta_code_f9f0ae_idx"),
                    models.Index(
                        fields=["is_active"], name="kitchen_sta_is_acti_a3d217_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Modifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Modifier group name", max_length=200),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=False,
                        help_text="Customer must select at least one option",
                    ),
                ),
                (
                    "max_selections",
                    models.IntegerField(
                        default=1,
                        help_text="Maximum selections allowed (0 = unlimited)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modifiers",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modifier",
                "verbose_name_plural": "Modifiers",
                "db_table": "modifier",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ModifierOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Price adjustment (e.g., +5000 for Large)",
                        max_digits=10,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, help_text="Default selection"),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="products.modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modifier Option",
                "verbose_name_plural": "Modifier Options",
                "db_table": "modifier_option",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PrinterConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("printer_name", models.CharField(max_length=200)),
                (
                    "ip_address",
                    models.GenericIPAddressField(help_text="Printer IP address"),
                ),
                (
                    "paper_width",
                    models.CharField(
                        choices=[("58mm", "58mm"), ("80mm", "80mm")],
                        default="80mm",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="printers",
                        to="products.kitchenstation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Printer Config",
                "verbose_name_plural": "Printer Configs",
                "db_table": "printer_config",
                "ordering": ["station", "printer_name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sku",
                    models.CharField(help_text="SKU unique per brand", max_length=50),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost for margin calculation",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "printer_target",
                    models.CharField(
                        choices=[
                            ("kitchen", "Kitchen"),
                            ("bar", "Bar"),
                            ("dessert", "Dessert"),
                        ],
                        default="kitchen",
                        help_text="Target printer for this product",
                        max_length=20,
                    ),
                ),
                (
                    "track_stock",
                    models.BooleanField(
                        default=False, help_text="Track inventory for this product"
                    ),
                ),
                (
                    "stock_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Current stock quantity (managed by Edge)",
                        max_digits=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="core.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "product",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProductModifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "modifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_modifiers",
                        to="products.modifier",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_modifiers",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "product_modifier",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("photo", models.ImageField(upload_to="product_photos/")),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary display photo"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Photo",
                "verbose_name_plural": "Product Photos",
                "db_table": "product_photo",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="TableArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="table_areas",
                        to="core.brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table Area",
                "verbose_name_plural": "Table Areas",
                "db_table": "table_area",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="Table number (e.g., A1, B5)", max_length=20
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        help_text="Maximum guests",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "qr_code",
                    models.CharField(
                        blank=True, help_text="QR code for ordering", max_length=200
                    ),
                ),
                (
                    "pos_x",
                    models.IntegerField(
                        blank=True, help_text="X position on floor plan", null=True
                    ),
                ),
                (
                    "pos_y",
                    models.IntegerField(
                        blank=True, help_text="Y position on floor plan", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("reserved", "Reserved"),
                        ],
                        default="available",
                        help_text="Status managed by Edge",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tables",
                        to="products.tablearea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
                "db_table": "table",
                "ordering": ["area", "number"],
            },
        ),
        migrations.CreateModel(
            name="TableGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="table_groups",
                        to="core.brand",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_table_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "main_table",
                    models.ForeignKey(
                        help_text="Primary table in group",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="main_table_groups",
                        to="products.table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table Group",
                "verbose_name_plural": "Table Groups",
                "db_table": "table_group",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TableGroupMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="group_memberships",
                        to="products.table",
                    ),
                ),
                (
                    "table_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="products.tablegroup",
                    ),
                ),
            ],
            options={
                "db_table": "table_group_member",
            },
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(
                fields=["brand", "is_active"], name="category_brand_i_1c495a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["parent"], name="category_parent__869b08_idx"),
        ),
        migrations.AddIndex(
            model_name="modifier",
            index=models.Index(
                fields=["brand", "is_active"], name="modifier_brand_i_e84568_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="modifieroption",
            index=models.Index(
                fields=["modifier", "is_active"], name="modifier_op_modifie_a1879c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="printerconfig",
            index=models.Index(
                fields=["station", "is_active"], name="printer_con_station_47ecec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["brand", "is_active"], name="product_brand_i_6eaab0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="product_categor_71bada_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["sku"], name="product_sku_afe0af_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("brand", "sku")},
        ),
        migrations.AddIndex(
            model_name="productmodifier",
            index=models.Index(
                fields=["product"], name="product_mod_product_76c6c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productmodifier",
            index=models.Index(
                fields=["modifier"], name="product_mod_modifie_2780a0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productmodifier",
            unique_together={("product", "modifier")},
        ),
        migrations.AddIndex(
            model_name="productphoto",
            index=models.Index(
                fields=["product", "is_primary"], name="product_pho_product_6ad96d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tablearea",
            index=models.Index(
                fields=["brand", "is_active"], name="table_area_brand_i_ae0a3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(
                fields=["area", "is_active"], name="table_area_id_ec7031_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="table",
            index=models.Index(fields=["number"], name="table_number_05c1f7_idx"),
        ),
        migrations.AddIndex(
            model_name="tablegroup",
            index=models.Index(
                fields=["brand", "created_at"], name="table_group_brand_i_1eacce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tablegroup",
            index=models.Index(
                fields=["main_table"], name="table_group_main_ta_d5c6ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tablegroupmember",
            index=models.Index(
                fields=["table_group"], name="table_group_table_g_16df03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tablegroupmember",
            index=models.Index(fields=["table"], name="table_group_table_i_a48db6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="tablegroupmember",
            unique_together={("table_group", "table")},
        ),
    ]
