# Generated by Django 5.0.1 on 2026-01-23 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_update_kitchenstation_add_brand"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="kitchenstation",
            new_name="kitchen_sta_brand_i_173560_idx",
            old_name="kitchen_sta_brand_i_0d8a44_idx",
        ),
        migrations.RenameIndex(
            model_name="kitchenstation",
            new_name="kitchen_sta_code_f9f0ae_idx",
            old_name="kitchen_sta_code_722d93_idx",
        ),
    ]
