# Generated by Django 5.0.1 on 2026-01-24 02:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_user_company"),
        (
            "products",
            "0003_rename_kitchen_sta_brand_i_0d8a44_idx_kitchen_sta_brand_i_173560_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="product",
            unique_together={("brand", "category", "name", "sku")},
        ),
    ]
