# Generated by Django 5.0.1 on 2026-01-24 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_user_company"),
        ("products", "0004_alter_product_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="company_products",
                to="core.company",
            ),
        ),
    ]
