# Generated by Django 5.0.1 on 2026-01-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Main product image",
                null=True,
                upload_to="product_images/",
            ),
        ),
    ]
