# Generated by Django 5.0.1 on 2026-01-25 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_add_store_to_tablearea"),
        ("products", "0006_product_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tablearea",
            options={
                "ordering": ["brand", "store", "sort_order", "name"],
                "verbose_name": "Table Area",
                "verbose_name_plural": "Table Areas",
            },
        ),
        migrations.AddField(
            model_name="tablearea",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of the area layout"
            ),
        ),
        migrations.AddField(
            model_name="tablearea",
            name="floor_height",
            field=models.IntegerField(
                blank=True, help_text="Floor height in pixels/units", null=True
            ),
        ),
        migrations.AddField(
            model_name="tablearea",
            name="floor_image",
            field=models.ImageField(
                blank=True,
                help_text="Floor plan image",
                null=True,
                upload_to="floor_plans/",
            ),
        ),
        migrations.AddField(
            model_name="tablearea",
            name="floor_width",
            field=models.IntegerField(
                blank=True, help_text="Floor width in pixels/units", null=True
            ),
        ),
        migrations.AddField(
            model_name="tablearea",
            name="store",
            field=models.ForeignKey(
                blank=True,
                help_text="Store-specific areas (leave blank for brand-wide)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="table_areas",
                to="core.store",
            ),
        ),
        migrations.AddIndex(
            model_name="tablearea",
            index=models.Index(
                fields=["store", "is_active"], name="table_area_store_i_27cc0c_idx"
            ),
        ),
    ]
