# Generated by Django 5.0.1 on 2026-01-25 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_update_kitchenstation_add_store_hierarchy"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="kitchenstation",
            new_name="kitchen_sta_store_i_4d6c03_idx",
            old_name="kitchen_sta_store_i_173560_idx",
        ),
    ]
